export const projectsData = [
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Landing Page",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Site Institucional",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
  {
    desktopUrl: "/images/projects-desktop-demo.png",
    desktopWidth: 1440,
    desktopHeight: 4756,
    mobileUrl: "/images/projects-mobile-demo.png",
    mobileWidth: 430,
    mobileHeight: 6048,
    category: "Plataforma",
    link: "https://www.mkdevsolutions.com/",
    title: "Título",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat quis lectus ut consequat. Vivamus eu turpis lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
  },
];
